config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :recipes
  resources :ingredients

  get '/users/:id/recipe_search', to: 'users#search', as: 'recipe_search'
  get '/users/:id/my_account', to: 'users#search', as: 'my_account'

  root "recipes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/direction.rb
class Direction < ApplicationRecord
  belongs_to :recipe
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :recipe_ingredients
  has_many :recipes, through: :recipe_ingredients

  validates :name, :ingredient_type, presence: true

  has_many :user_ingredients
  has_many :users, through: :user_ingredients
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :directions
  has_many :recipe_ingredients
  has_many :ingredients, through: :recipe_ingredients

  accepts_nested_attributes_for :directions, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :recipe_ingredients, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :ingredients, reject_if: :all_blank, allow_destroy: true

  validates :title, :description, presence: true

  mount_uploader :image, ImageUploader
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
  belongs_to :recipe
  belongs_to :ingredient
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :recipes
  has_many :user_ingredients
  has_many :ingredients, through: :user_ingredients

  accepts_nested_attributes_for :user_ingredients, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :ingredients, reject_if: :all_blank, allow_destroy: true

  def beef_function

    ui = self.ingredients
    available_recipes = []

    Recipe.all.each do |recipe|
      if !(ui & recipe.ingredients).empty? && (ui & recipe.ingredients).length == recipe.ingredients.length
        available_recipes << recipe
      end
    end
    available_recipes
  end

end #end of User class

app/models/user_ingredient.rb
class UserIngredient < ApplicationRecord
  belongs_to :user
  belongs_to :ingredient
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :find_ingredient, only: [:show, :edit, :update, :destroy]

  def index
    @ingredients = Ingredient.all
  end

  def show

  end

  def new
    @ingredient = Ingredient.new
  end

  def create
    @ingredient = Ingredient.create(ingredient_params)

    if @ingredient.save
      redirect_to @ingredient, notice: "Successfully created ingredient"
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @ingredient.update(ingredient_params)
      redirect_to @ingredient
    else
      render 'edit'
    end
  end

  def destroy
    @ingredient.destroy
    redirect_to ingredients_path, notice: "Successfully deleted ingredient"
  end

  private

  def ingredient_params
    params.require(:ingredient).permit(:name, :ingredient_type, recipe_ingredients_attributes: [:id, :_destroy])
  end

  def find_ingredient
    @ingredient = Ingredient.find(params[:id])
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :find_recipe, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @recipes = Recipe.all.order("created_at DESC")
  end

  def show
  end

  def new
    @recipe = current_user.recipes.build
    @ingredients = Ingredient.all

    @recipe.recipe_ingredients.build
    @recipe.directions.build
  end

  def create
    @ingredients = Ingredient.all
    @recipe = current_user.recipes.build(recipe_params)

    if @recipe.save
      # params[:recipe][:recipe_ingredients_attributes].each do |recipe_ingredient_attribute|
      #     RecipeIngredient.create(recipe_id:@recipe.id, ingredient_id:recipe_ingredient_attribute[1][:ingredient_id], amount:recipe_ingredient_attribute[1][:amount])
      # end

      redirect_to @recipe, notice: "Successfully created recipe"
    else
      render 'new'
    end
  end

  def edit
    @ingredients = Ingredient.all
  end

  def update
    if @recipe.update(recipe_params)
      redirect_to @recipe
    else
      render 'edit'
    end
  end

  def destroy
    @recipe.destroy
    redirect_to root_path, notice: "Successfully deleted recipe"
  end

  private

  def find_recipe
    @recipe = Recipe.find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(:remove_image, :image, :title, :description, directions_attributes: [:id, :step, :_destroy], recipe_ingredients_attributes: [:id, :user_id, :recipe_id, :ingredient_id, :amount, :_destroy], ingredients_attributes: [:id, :name, :_destroy])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show, :edit, :update, :search]

  def show
  end

  def edit
    @user.user_ingredients.build
    @ingredients = Ingredient.all
  end

  def update
    if @user.update(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

  def search
    @available_recipes = @user.beef_function
  end

  private

  def find_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(user_ingredients_attributes: [:id, :user_id, :ingredient_id, :_destroy], ingredients_attributes: [:id, :name, :_destroy])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/user_ingredients_helper.rb
module UserIngredientsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ingredients/_form.erb
<%= simple_form_for @ingredient, html: { multipart: true } do |f| %>

  <% if @ingredient.errors.any? %>
    <p>
      <%= @ingredient.errors.count %>
      Prevented this ingredient from saving
    </p>
    <ul>
      <% @ingredient.errors.full_message.each do |msg| %>
        <li> <%= msg %>
      <% end %>
  <% end %>

  <div class="panel-body">
    <%= f.input :name, input_html: { class: 'form-control' } %>
    <%= f.input :ingredient_type, input_html: { class: 'form-control' } %>
  </div>

  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/ingredients/edit.erb
<h1>Edit Ingredient</h1>
<%= render 'form' %>

app/views/ingredients/index.erb
<% if user_signed_in? %>
  <div class="button-container">
    <%= link_to "Click Here to Make a New Ingredient", new_ingredient_path, class: "btn btn-primary btn-block" %><br>
  </div>
<% end %>

<div class="container">
  <div class="row">
    <% @ingredients.each do |ingredient| %>
      <div class="col-md-4">
        <div class="ingredient-box">
          <%= link_to ingredient.name, ingredient %>
            <% if current_user && recipe.user_id == current_user.id %>
          <%= link_to "Edit", "/ingredient/#{ingredient.id}/edit", class: "btn btn-default btn-xs" %>
          <%= link_to "Delete", "/ingredients/#{ingredient.id}", method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default btn-xs" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/ingredients/new.erb
<h1>New Ingredient</h1>

<%= render 'form' %><br>

<%= link_to "Back", ingredients_path, class: "btn btn-default" %>

app/views/ingredients/show.erb
<h2><%= @ingredient.name %></h2>
<p><%= @ingredient.ingredient_type %></p>

<% if user_signed_in? %>
  <%= link_to "Back", ingredients_path, class: "btn btn-default" %>
  <%= link_to "New", new_ingredient_path, class: "btn btn-default" %>
  <%= link_to "Edit", edit_ingredient_path, class: "btn btn-default"  %>
  <%= link_to "Delete", ingredient_path, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default" %>
<% else %>
  <%= link_to "Back", ingredients_path, class: "btn btn-default" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FÜD</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="/" >FÜD</a>
        </div>
        <ul class="nav navbar-nav">
          <li class="active"><a href="/">Home</a></li>
          <li><a href="/recipes">Recipes</a></li>
          <li><a href="/ingredients">Ingredients</a></li>
        </ul>

        <% if user_signed_in? %>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to('My Cupboard', user_path(current_user.id)) %></li>
            <li><%= link_to('Search', recipe_search_path(current_user.id)) %></li>
            <li><%= link_to('My Account', my_account_path(current_user.id)) %></li>
            <li><%= link_to('Logout', destroy_user_session_path, method: :delete) %></li>
          </ul>
        <% else %>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="/users/sign_up"><span class="glyphicon glyphicon-user"></span> Sign Up </a></li>
            <li><a href="/users/sign_in"><span class="glyphicon glyphicon-log-in"></span> Login </a></li>
          </ul>
        <% end %>

      </div>
    </nav>

    <div id="under-nav" class="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, class: "alert" %>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/recipes/_direction_fields.erb
<div class="nested-fields">
  <div class="form-group">
    <li>
      <%= f.text_area :step, class: "form-control" %>
      <%= link_to_remove_association "remove", f %>
    </li>
  </div>
</div>

app/views/recipes/_form.erb
<% if @recipe.errors.any? %>
    <ul>
    <% @recipe.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
<% end %>

<%= form_for @recipe do |f| %>

<div class="form-group">

  <% if @recipe.image? %>
    <%= image_tag @recipe.image.url, class: "recipe-show" %>
    <%= f.check_box :remove_image %>
    Remove Image
  <% end %>
  <%= f.file_field :image %>
</div>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %><br>

    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control" %>
  </div>

  <div class="ingredients">
    <h2>Ingredients</h2>

    <%= f.label :name %>
    <%= f.fields_for :recipe_ingredients do |ri| %>
      <%= render 'recipe_ingredient_fields', f: ri %>

      <div class="links">
        <%= link_to_add_association 'add ingredient', f, :recipe_ingredients %>

      </div>
    <% end %>
  </div>

  <div id="directions">
    <h2>Directions</h2>

    <%= f.label "Step(s)" %>
    <ol>
      <%= f.fields_for :directions do |direction| %>
        <%= render 'direction_fields', f: direction %>

        <div class="links">
          <%= link_to_add_association 'add step', f, :directions %>
        </div>
      <% end %>
    </ol>
  </div>

  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/recipes/_recipe_ingredient_fields.erb
<div class="nested-fields">
  <div class="field">
    <%= f.collection_select :ingredient_id, @ingredients, :id, :name %>
    <%= f.text_field :amount %>
    <%= link_to_remove_association "remove", f %>
  </div>
</div>

app/views/recipes/edit.erb
<h1>Edit Recipe</h1>
<%= render 'form' %>

app/views/recipes/index.erb
<% if user_signed_in? %>
  <div class="button-container">
    <%= link_to "Click Here to Make a New Recipe", new_recipe_path, class: "btn btn-primary btn-block" %><br>
  </div>
<% end  %>

<div class="container">
  <div class="row">
    <% @recipes.each do |recipe| %>
    <div class="col-md-4">
      <div class="recipe-box">
        <% if recipe.image? %>
          <%= link_to (image_tag recipe.image.url, class: "recipe-index"), recipe %>
        <% end %>
          <h3><%= link_to recipe.title, recipe %></h3>
          <%= recipe.description %><br>

          <% if current_user && recipe.user_id == current_user.id %>
            <%= link_to "Edit", "/recipes/#{recipe.id}/edit", class: "btn btn-default btn-xs" %>
            <%= link_to "Delete", "/recipes/#{recipe.id}", method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default btn-xs" %>
          <% end %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/recipes/new.erb
<h1>New Recipe</h1>

<%= render 'form' %>

<br>

<%= link_to "Back", root_path, class: "btn btn-default" %>

app/views/recipes/show.erb
<% if @recipe.image? %>
  <%= image_tag @recipe.image.url, class: "recipe-show" %>
<% end %>

<h1><%= @recipe.title %></h1>
<p>Written by <%= @recipe.user.email %></p>
<p><%= @recipe.description %></p>

<h2>Ingredients</h2>
<ol>
  <% @recipe.ingredients.each do |ingredient| %>
    <% @recipe.recipe_ingredients.map do |recipe_ingredient| %>
      <% if recipe_ingredient.ingredient_id == ingredient.id %>
        <%= "#{ingredient.name}, #{recipe_ingredient.amount}" %><br>
      <% end %>
    <% end %>
  <% end %>
</ol>

<h2>Directions</h2>
<ol>
  <% @recipe.directions.each do |direction| %>
    <li><%= direction.step %></li><br>
  <% end %>
</ol>

<% if user_signed_in? && @recipe.user_id == current_user.id %>
  <%= link_to "Back", root_path, class: "btn btn-default" %>
  <%= link_to "New", new_recipe_path, class: "btn btn-default" %>
  <%= link_to "Edit", edit_recipe_path, class: "btn btn-default"  %>
  <%= link_to "Delete", recipe_path, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default" %>
<% else %>
  <%= link_to "Back", root_path, class: "btn btn-default" %>
<% end %>

app/views/users/_form.erb
<%= form_for @user do |f| %>

  <div class="ingredients">
    <h2>Ingredients</h2>

    <%= f.label :name %>
    <%= f.fields_for :user_ingredients do |ui| %>

    <%= render 'user_ingredient_fields', f: ui %>

    <div class="links">
      <%= link_to_add_association 'add ingredient', f, :user_ingredients %>
    </div>
  <% end %>
  </div>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/users/_user_ingredient_fields.erb
<div class="nested-fields">
  <div class="field">
    <%= f.collection_select :ingredient_id, @ingredients, :id, :name %>
    <%= link_to_remove_association "remove", f %>
  </div>
</div>

app/views/users/edit.erb
<h1>Edit My Cupboard</h1>
<%= render 'form' %>

app/views/users/search.erb
<% if @available_recipes.any? %>
  <h2>These are recipes you can cook with the ingredients in your cupboard!</h2>

  <div class="container">
    <div class="row">


    <% @available_recipes.each do |recipe| %>
      <div class="col-md-4">
        <div class="recipe-box">
          <% if recipe.image? %>
            <%= link_to (image_tag recipe.image.url, class: "recipe-index"), recipe %>
          <% end %>
            <h3><%= link_to recipe.title, recipe %></h3>
            <%= recipe.description %><br>
        </div>
      </div>
    <% end %>
    </div>
  </div>
  <% else %>
  <h2>No recipes match your ingredients! You will need to add ingredients to your cupboard.</h2>
  <%= link_to('Click Here to see your Cupboard', user_path(current_user.id), class: "btn btn-primary") %>
<% end %>

app/views/users/show.erb
<h1>My Cupboard</h1>

<ol>
  <% @user.ingredients.each do |ingredient| %>
    <%= ingredient.name %><br>

  <% end %>
</ol>

<%= link_to "Edit My Cupboard", "/users/#{@user.id}/edit", class: "btn btn-default btn-xs" %>

<%= link_to "Show Me Recipes I Can Cook Right Now!", recipe_search_path, class: "btn btn-default btn-xs" %>